server:
  port: 8040

spring:
  application:
    name: menuService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/second_project?serverTimezone=UTC&characterEncoding=UTF-8
    username: hellsfood
    password: a802
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: mongodb-container
      port: 27017
      database: hell