spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
  mail:
    username: ${env.SPRING_MAIL_USERNAME}
    port: 465
    properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
    host: ${env.SPRING_MAIL_HOST}
    password: ${env.SPRING_MAIL_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a802
    username: hellsfood
    url: jdbc:mysql://mysql-container:3306/project2db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  data:
    mongodb:
      host: mongodb-container
      port: 27017
      authentication-database: project2db
      uri: mongodb://mongodb-container:27017/
  devtools:
    livereload:
      enabled: true
  application:
    name: userService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - credentials
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: ERROR
        security: DEBUG
      apache:
        tiles: INFO
    root: INFO
  file:
    name: './BE_user.log'
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 8011
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
springfox:
  documentation:
    swagger:
      use-model-v3: false
jwt:
  secret: IfYouLeftYourFoodYouWillEatYourRemainsInHell
